source $HOME/.zprezto/runcoms/zshrc
export YADR_PATH="$HOME/src/github.com/murawakimitsuhiro/dotfiles"
for config_file ($YADR_PATH/zsh/*.zsh) source $config_file
eval "$(pyenv init --path)"
eval "$(pyenv init --path)"
eval "$(pyenv init --path)"
eval "$(pyenv init --path)"
eval "$(pyenv init --path)"
eval "$(pyenv init --path)"
